### ISSUE TITLE
efficient pairing in sCrypt

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/zokrates#24]
Let's implement pairing used in [ETH](https://github.com/ethereum/go-ethereum/blob/master/crypto/bn256/cloudflare/bn256.go), based on these 2 papers:
[New software speed records for cryptographic pairings](https://github.com/ethereum/go-ethereum/blob/9a5c1000c73c39e036973f4dfa828acc707e6d7c/crypto/bn256/google/optate.go#L191)
[Faster Computation of the Tate Pairing](https://arxiv.org/pdf/0904.0854v3.pdf)

Another less optimized python implm: [py_pairing](https://github.com/ethereum/py_pairing/blob/master/py_ecc/optimized_bn128/optimized_pairing.py)

**Comment by msinkec** [comment]
My current work is in this repo: https://github.com/msinkec/scrypt-pairing
Will add to boilerplate repo soon.
